Feat/add strict mode
SovereignCloudStack/github-permissions pull request #18
Opened 2022-07-28 09:46 UTC by fkr

2022-07-28 09:47 UTC, tibeer reviewed
LGTM! No DCO though.

2022-07-28 12:48 UTC, tibeer requested changes
See comments. Still no DCO.

2022-07-28 12:48 UTC, tibeer commented on manage.py
> +                break
This break terminates only one for loop. Even tough this code will work, it looks unfriendly to maintain. Maybe rewrite completely?

2022-07-28 12:51 UTC, fkr commented on manage.py
> +                break
it is meant to only break one ;

2022-07-28 12:52 UTC, fkr commented
> LGTM! No DCO though.

yes, one commit is missing the DCO. all others have it.

2022-07-28 12:57 UTC, tibeer commented on manage.py
> +                break
Suggestion:

old
```py
    milestone_found= False
    for milestone in CONFIG['milestones']:

        for gh_milestone in gh_milestones:
            if milestone == gh_milestone.title:
                logging.info(f"{gh_repository.name} - milestone {milestone} does exist")
                milestone_found= True
                break
    if milestone_found is False:
        logging.info(f"{gh_repository.name} - milestone {milestone} does not exist")
        if args.dry is False:
            gh_repository.create_milestone(title=milestone, state="open")
```

new
```py
    for milestone in CONFIG['milestones']:
        if milestone in gh_milestones:
            logging.info(f"{gh_repository.name} - milestone {milestone} does exist")
        else:
            logging.info(f"{gh_repository.name} - milestone {milestone} does not exist")
            if args.dry is False:
                gh_repository.create_milestone(title=milestone, state="open")
```

2022-07-28 13:19 UTC, tibeer commented
Fixed DCO check.

2022-07-28 14:43 UTC, tibeer commented on manage.py
> +                break
Crap, you are right. Will look into it.

2022-07-28 14:47 UTC, fkr commented on manage.py
> +                break
🤷 why can't we use what I proposed?

2022-07-28 14:51 UTC, tibeer commented on manage.py
> +                break
If you loop all milestones from the config and there is one, which is not present, it will not get created if there was one previous that existed.

2022-07-28 15:05 UTC, tibeer commented on manage.py
> +                break
there is still an issue. Once both loops are done, you don't have access to "milestone" any more. So it needs to be moved into the first loop.

2022-07-28 15:13 UTC, tibeer commented on manage.py
> +                break
Possible other solution:s

solution 1

```py

    for milestone in CONFIG['milestones']:
        milestone_found= False

        for gh_milestone in gh_milestones:
            if milestone == gh_milestone.title:
                logging.info(f"{gh_repository.name} - milestone {milestone} does exist")
                milestone_found= True
                break

        if milestone_found is False:
            logging.info(f"{gh_repository.name} - milestone {milestone} does not exist")
            if args.dry is False:
                gh_repository.create_milestone(title=milestone, state="open")
```

solution 2

```py
    gh_milestone_titles = []
    for gh_milestone in gh_milestones:
        gh_milestone_titles.append(gh_milestone.title)

    for milestone in CONFIG['milestones']:
        if milestone in gh_milestone_titles:
            logging.info(f"{gh_repository.name} - milestone {milestone} does exist")
        else:
            logging.info(f"{gh_repository.name} - milestone {milestone} does not exist")
            if args.dry is False:
                gh_repository.create_milestone(title=milestone, state="open")

```

2022-07-28 15:21 UTC, fkr commented on manage.py
> +                break
thanks @tibeer. imho solution 2 makes the most sense. can you push it on top of this branch? that is a good one, imho.

2022-07-29 06:27 UTC, fkr commented
awesome @tibeer - thanks for this nice collaboration.

2022-07-29 06:29 UTC, merged